---
- name: Restart nginx
  hosts: all

  sources:
    - name: webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Restart nginx
      condition: event.payload is defined
      action:
        run_job_template:
          name: Restart nginx
          organization: Default